### ISSUE TITLE
FR: Opacity transition on text

### ISSUE THREAD

**Issue by lukepighetti** [sooxt98/google_nav_bar#15] opened 2020-05-16 18:53 UTC
We have a feature request to have an opacity transition on the text with its own curve and duration. Is this a feature you would consider adding?

**Comment by sooxt98** [comment] 2020-05-16 19:00
Do you mean the Crossfade transition? Currently no, I think it's enough for normal usage, and I think is kinda perfect. Feel free to pull request

**Comment by lukepighetti** [comment] 2020-05-17 02:36
It looks really janky with outlined icons.

**Comment by sooxt98** [comment] 2020-05-17 17:16
That's by design which match with the dribble animation. Maybe u could show me the difference, or maybe do an option to disable that crossfade

**Comment by lukepighetti** [comment] 2020-05-17 17:31
If you look at the design specced here: https://dribbble.com/shots/5925052-Google-Bottom-Bar-Navigation-Pattern/

You will see that the text is never visible behind the icons. `google_nav_bar` does not adhere to the spec as it allows the text to be visible behind the icon when transitioning. I'm asking for controls to allow us to guarantee that the text doesn't appear behind the icon.

**Comment by sooxt98** [comment] 2020-05-17 17:41
Look at the search icon.

**Comment by lukepighetti** [comment] 2020-05-17 17:44
Not sure what you mean. The dribbble spec still guarantees that the text is never visible behind the icon. Am I misunderstanding what you're talking about? 

<img width="675" alt="Screen Shot 2020-05-17 at 1 43 41 PM" src="https://user-images.githubusercontent.com/666539/82155648-6d77fe80-9844-11ea-9619-bcd96fac76ca.png">

**Comment by sooxt98** [comment] 2020-05-17 17:44
![image](https://user-images.githubusercontent.com/13378059/82155657-1b1cf900-98a9-11ea-88af-5afa659de4d9.png)
i think need to tweak the timing abit

**Comment by lukepighetti** [comment] 2020-05-17 17:45
That was the intent of this FR was to allow us to control the timing of the opacity transition so you don't have to fiddle with it.

**Comment by sooxt98** [comment] 2020-05-17 17:49
yep feel free to pull request, ill merge it if it looks good

**Comment by sooxt98** [comment] 2020-05-17 18:09
I think the problem is not only the opcity, and the offset of from the start

**Comment by sooxt98** [comment] 2020-05-19 09:57
@lukepighetti by the way it doesn't shows overlay problem at my pen, may i know what kind of settings you used for your situation?

https://codepen.io/soo-xiao-tong/pen/zYvpNZw

**Comment by lukepighetti** [comment] 2020-05-19 10:54
We are no longer using this package so you’re welcome to close this issue.

**Comment by sooxt98** [comment] 2020-08-19 17:18
Fixed in V3

**Closed by sooxt98** 2020-08-19 17:18 UTC
Labels: enhancement
